import Header from '@/components/Header';
import './globals.css';
import { DM_Mono } from 'next/font/google';
import ActiveSectionContextProvider from '@/context/active-section-context';

const dm_mono = DM_Mono({ weight: '400', subsets: [] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body
        className={`${dm_mono.className} bg-[#e5e7eb] text-gray-950 relative py-0 md:py-3 text-md md:text-lg`}
      >
        <ActiveSectionContextProvider>
          <Header />
          {children}
        </ActiveSectionContextProvider>
      </body>
    </html>
  );
}
